### PR TITLE
Adds sponsors

### PR DESCRIPTION
**Pull request by Josh-00FF00**

### CODE REVIEW

**Comment by qaisjp** [comment]
Is bootstrap used anywhere? Looking at the code I don't see it...

**Review by neanias — COMMENTED** [review]
What's the Bloomberg EPS file for?

**Comment by qaisjp** [comment]
The Bloomberg logo was provided as an EPS (according to the compsoc Google
drive)

**Comment by neanias** [comment]
Ok, but why keep it if we're not using it?

**Comment by qaisjp** [comment]
No reason.

**Comment by neanias** [comment]
Then get rid of it, @JoshGreen1337

**Review by hreeder — COMMENTED** [review]
Why is bootstrap included in full here?

**Comment by Josh-00FF00** [comment]
Huh I was testing that (bootstrap that is) and was pretty sure I had it removed, clearly I didn't :/

Either way removed that now. Teaches me for pushing at 4am

**Comment by hreeder** [comment]
Code looks good to me, I'll pull it down and check it visually some point today

**Comment by neanias** [comment]
Please can we keep commit messages tidy and in the proper form

**Review by neanias — APPROVED** [review]
LGTM

**Review by hreeder — APPROVED** [review]

**Pull request merged**
